version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/jre-1.7.0-openjdk"

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the modified-tracker
    - pwd
    - mvn -version
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  - appspec.yml
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'
